site_name: VideoOS lua app
repo_url: https://github.com/VideoOS/VideoOS-lua-app
markdown_extensions:
  - admonition
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
nav:
  - 'get started': 'get_started.md'
  - 'View（视图）':
    - 'Alert（对话框组件）': 'API/Lua_View/Alert.md'
    - 'Animation（动画组件）': 'API/Lua_View/Animation.md'
    - 'Button（按钮组件）': 'API/Lua_View/Button.md'
    - 'Canvas（自定义绘制组件）': 'API/Lua_View/Canvas.md'
    - 'CollectionView（列表组件）': 'API/Lua_View/CollectionView.md'
    - 'CustomPanel（自定义组件）': 'API/Lua_View/CustomPanel.md'
    - 'HScrollView（横向滑动组件）': 'API/Lua_View/HScrollView.md'
    - 'Image（图片组件）': 'API/Lua_View/Image.md'
    - 'Label（文本组件）': 'API/Lua_View/Label.md'
    - 'LoadingDialog（加载对话框组件）': 'API/Lua_View/LoadingDialog.md'
    - 'LoadingIndicator（加载指示器组件）': 'API/Lua_View/LoadingIndicator.md'
    - 'Navigation（导航条组件）': 'API/Lua_View/Navigation.md'
    - 'PagerIndicator（页面组指示器组件）': 'API/Lua_View/PagerIndicator.md'
    - 'PagerView（页面组组件）': 'API/Lua_View/PagerView.md'
    - 'RefreshCollectionView（可刷新列表组件）': 'API/Lua_View/RefreshCollectionView.md'
    - 'RefreshTableView（可刷新列表组件）': 'API/Lua_View/RefreshTableView.md'
    - 'ScrollView（基础列表组件）': 'API/Lua_View/ScrollView.md'
    - 'StyledString（富文本组件）': 'API/Lua_View/StyledString.md'
    - 'SVGAView（svga组件）': 'API/Lua_View/SVGAView.md'
    - 'TableView（基础列表组件）': 'API/Lua_View/TableView.md'
    - 'TextFiled（输入框组件）': 'API/Lua_View/TextFiled.md'
    - 'Toast（提示信息组件）': 'API/Lua_View/Toast.md'
    - 'View（视图组建）': 'API/Lua_View/View.md'
    - 'WebView（html组件）': 'API/Lua_View/WebView.md'
    - 'AppLet（B类小程序容器）': 'API/Lua_View/AppLet.md'
  - 'Bridge（桥接组件）':
    - 'AudioPlayer（音频播放器组件）': 'API/Lua_Bridge/AudioPlayer.md'
    - 'Data（二进制数据组件）': 'API/Lua_Bridge/Data.md'
    - 'File（文件操作组件）': 'API/Lua_Bridge/File.md'
    - 'Http（网络组件）': 'API/Lua_Bridge/Http.md'
    - 'Json（Json组件）': 'API/Lua_Bridge/Json.md'
    - 'Media（监听播放器状态组件）': 'API/Lua_Bridge/Media.md'
    - 'Mqtt（监听和控制Mqtt业务组件）': 'API/Lua_Bridge/Mqtt.md'
    - 'Native（提供原生功能组件）': 'API/Lua_Bridge/Native.md'
    - 'Page（监听页面的生命周期状态组件）': 'API/Lua_Bridge/Page.md'
    - 'System（系统信息组件）': 'API/Lua_Bridge/System.md'
    - 'Timer（定时器组件）': 'API/Lua_Bridge/Timer.md'
    - 'Vibrator（震动组件）': 'API/Lua_Bridge/Vibrator.md'
  - 'Constants（样式）':
    - 'Align（方向布局样式）': 'API/Lua_Constants/Align.md'
    - 'Ellipsize（文本省略样式）': 'API/Lua_Constants/Ellipsize.md'
    - 'FontStyle（字体样式）': 'API/Lua_Constants/FontStyle.md'
    - 'FontWeight（字体大小样式）': 'API/Lua_Constants/FontWeight.md'
    - 'Gravity（布局样式）': 'API/Lua_Constants/Gravity.md'
    - 'Interpolator（动画差值器样式）': 'API/Lua_Constants/Interpolator.md'
    - 'PaintStyle（Canvas画笔样式）': 'API/Lua_Constants/PaintStyle.md'
    - 'ScaleType（图片样式）': 'API/Lua_Constants/ScaleType.md'
    - 'TextAlign（文本布局样式）': 'API/Lua_Constants/TextAlign.md'
    - 'ViewEffect（View特效样式）': 'API/Lua_Constants/ViewEffect.md'
  - 'Demo':
    - 'demo_FlexBox': 'API/Lua_Demo/demo_FlexBox.md'
    - 'demo_Hello': 'API/Lua_Demo/demo_Hello.md'
    - 'demo_Image': 'API/Lua_Demo/demo_Image.md'
    - 'demo_ImageAnimate': 'API/Lua_Demo/demo_ImageAnimate.md'
    - 'demo_ViewChildren': 'API/Lua_Demo/demo_ViewChildren.md'
    - 'demo_Bitmap': 'API/Lua_Demo/demo_Bitmap.md'
    - 'demo_Label': 'API/Lua_Demo/demo_Label.md'
    - 'demo_IconFontLabel': 'API/Lua_Demo/demo_IconFontLabel.md'
    - 'demo_requestFromHttp': 'API/Lua_Demo/demo_requestFromHttp.md'
    - 'demo_Button': 'API/Lua_Demo/demo_Button.md'
    - 'demo_CollectionView': 'API/Lua_Demo/demo_CollectionView.md'
    - 'demo_EmptyRefreshCollectionView': 'API/Lua_Demo/demo_EmptyRefreshCollectionView.md'
    - 'demo_PagerView': 'API/Lua_Demo/demo_PagerView.md'
    - 'demo_ScrollView': 'API/Lua_Demo/demo_ScrollView.md'
    - 'demo_WebView': 'API/Lua_Demo/demo_WebView.md'
    - 'demo_Alert': 'API/Lua_Demo/demo_Alert.md'
    - 'demo_LoadingIndicator': 'API/Lua_Demo/demo_LoadingIndicator.md'
    - 'demo_CustomView': 'API/Lua_Demo/demo_CustomView.md'
    - 'demo_onTouch': 'API/Lua_Demo/demo_onTouch.md'
    - 'demo_Navigation': 'API/Lua_Demo/demo_Navigation.md'
    - 'demo_coroutine': 'API/Lua_Demo/demo_coroutine.md'
    - 'demo_table': 'API/Lua_Demo/demo_table.md'
    - 'demo_Timer': 'API/Lua_Demo/demo_Timer.md'
    - 'demo_Http': 'API/Lua_Demo/demo_Http.md'
    - 'demo_Json': 'API/Lua_Demo/demo_Json.md'
    - 'demo_string': 'API/Lua_Demo/demo_string.md'
    - 'demo_System': 'API/Lua_Demo/demo_System.md'
    - 'demo_CustomError': 'API/Lua_Demo/demo_CustomError.md'
    - 'demo_Customloading': 'API/Lua_Demo/demo_Customloading.md'
    - 'demo_shake': 'API/Lua_Demo/demo_shake.md'
    - 'demo_AudioPlayer': 'API/Lua_Demo/demo_AudioPlayer.md'
    - 'demo_flxNode': 'API/Lua_Demo/demo_flxNode.md'
    - 'demo_DownloadAndFile': 'API/Lua_Demo/demo_DownloadAndFile.md'
    - 'demo_testunits': 'API/Lua_Demo/demo_testunits.md'
    - 'demo_decodeUrl': 'API/Lua_Demo/demo_decodeUrl.md'
    - 'demo_Gesture': 'API/Lua_Demo/demo_Gesture.md'
    - 'demo_testunit': 'API/Lua_Demo/demo_testunit.md'
    - 'demo_luabox': 'API/Lua_Demo/demo_luabox.md'
    - 'demo_callOC': 'API/Lua_Demo/demo_callOC.md'
    - 'demo_Animator': 'API/Lua_Demo/demo_Animator.md'
    - 'demo_matrix': 'API/Lua_Demo/demo_matrix.md'
    - 'demo_init': 'API/Lua_Demo/demo_init.md'
    - 'demo_testunit': 'API/Lua_Demo/demo_testunit.md'
