site_name: VideoOS-lua-app
nav:
  - 'OS_Lua 简介': 'OS_Lua.md'
  - 'Android集成说明': 'Android.md'
  - 'iOS集成说明': 'iOS.md'
  - 'lua_View':
     - 'Alert': 'API/Lua_View/Alert.md'
     - 'Animation': 'Animation.md'
     - 'Button': 'Button.md'
     - 'Canvas': 'Canvas.md'
     - 'CollectionView': 'CollectionView.md'
     - 'CustomPanel': 'CustomPanel.md'
     - 'HScrollView': 'HScrollView.md'
     - 'Image': 'Image.md'
     - 'Label': 'Label.md'
     - 'LoadingDialog': 'LoadingDialog.md'
     - 'LoadingIndicator': 'LoadingIndicator.md'
     - 'Navigation': 'Navigation.md'
     - 'PagerIndicator': 'PagerIndicator.md'
     - 'PagerView': 'PagerView.md'
     - 'RefreshCollectionView': 'RefreshCollectionView.md'
     - 'RefreshTableView': 'RefreshTableView.md'
     - 'ScrollView': 'ScrollView.md'
     - 'StyledString': 'StyledString.md'
     - 'SVGAView': 'SVGAView.md'
     - 'TableView': 'TableView.md'
     - 'TextFiled': 'TextFiled.md'
     - 'Toast': 'Toast.md'
     - 'View': 'View.md'
     - 'WebView': 'WebView.md'
  - 'Lua_Bridge':
     - 'AudioPlayer': 'AudioPlayer.md'
     - 'Data': 'Data.md'
     - 'File': 'File.md'
     - 'Http': 'Http.md'
     - 'Json': 'Json.md'
     - 'Media': 'Media.md'
     - 'Mqtt': 'Mqtt.md'
     - 'Native': 'Native.md'
     - 'Page': 'Page.md'
     - 'System': 'System.md'
     - 'Timer': 'Timer.md'
     - 'Vibrator': 'Vibrator.md'
  - 'Lua_Constants':
     - 'Align': 'Align.md'
     - 'Ellipsize': 'Ellipsize.md'
     - 'FontStyle': 'FontStyle.md'
     - 'FontWeight': 'FontWeight.md'
     - 'Gravity': 'Gravity.md'
     - 'Interpolator': 'Interpolator.md'
     - 'PaintStyle': 'PaintStyle.md'
     - 'ScaleType': 'ScaleType.md'
     - 'TextAlign': 'TextAlign.md'
     - 'ViewEffect': 'ViewEffect.md'


