site_name: VideoOS lua app
repo_url: https://github.com/VideoOS/VideoOS-lua-app
markdown_extensions:
  - admonition
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
nav:
  - 'OS_Lua': 'OS_Lua.md'
  - 'lua_View':
     - 'Alert': 'API/Lua_View/Alert.md'
     - 'Animation': 'API/Lua_View/Animation.md'
     - 'Button': 'API/Lua_View/Button.md'
     - 'Canvas': 'API/Lua_View/Canvas.md'
     - 'CollectionView': 'API/Lua_View/CollectionView.md'
     - 'CustomPanel': 'API/Lua_View/CustomPanel.md'
     - 'HScrollView': 'API/Lua_View/HScrollView.md'
     - 'Image': 'API/Lua_View/Image.md'
     - 'Label': 'API/Lua_View/Label.md'
     - 'LoadingDialog': 'API/Lua_View/LoadingDialog.md'
     - 'LoadingIndicator': 'API/Lua_View/LoadingIndicator.md'
     - 'Navigation': 'API/Lua_View/Navigation.md'
     - 'PagerIndicator': 'API/Lua_View/PagerIndicator.md'
     - 'PagerView': 'API/Lua_View/PagerView.md'
     - 'RefreshCollectionView': 'API/Lua_View/RefreshCollectionView.md'
     - 'RefreshTableView': 'API/Lua_View/RefreshTableView.md'
     - 'ScrollView': 'API/Lua_View/ScrollView.md'
     - 'StyledString': 'API/Lua_View/StyledString.md'
     - 'SVGAView': 'API/Lua_View/SVGAView.md'
     - 'TableView': 'API/Lua_View/TableView.md'
     - 'TextFiled': 'API/Lua_View/TextFiled.md'
     - 'Toast': 'API/Lua_View/Toast.md'
     - 'View': 'API/Lua_View/View.md'
     - 'WebView': 'API/Lua_View/WebView.md'
  - 'Lua_Bridge':
     - 'AudioPlayer': 'API/Lua_Bridge/AudioPlayer.md'
     - 'Data': 'API/Lua_Bridge/Data.md'
     - 'File': 'API/Lua_Bridge/File.md'
     - 'Http': 'API/Lua_Bridge/Http.md'
     - 'Json': 'API/Lua_Bridge/Json.md'
     - 'Media': 'API/Lua_Bridge/Media.md'
     - 'Mqtt': 'API/Lua_Bridge/Mqtt.md'
     - 'Native': 'API/Lua_Bridge/Native.md'
     - 'Page': 'API/Lua_Bridge/Page.md'
     - 'System': 'API/Lua_Bridge/System.md'
     - 'Timer': 'API/Lua_Bridge/Timer.md'
     - 'Vibrator': 'API/Lua_Bridge/Vibrator.md'
  - 'Lua_Constants':
     - 'Align': 'API/Lua_Constants/Align.md'
     - 'Ellipsize': 'API/Lua_Constants/Ellipsize.md'
     - 'FontStyle': 'API/Lua_Constants/FontStyle.md'
     - 'FontWeight': 'API/Lua_Constants/FontWeight.md'
     - 'Gravity': 'API/Lua_Constants/Gravity.md'
     - 'Interpolator': 'API/Lua_Constants/Interpolator.md'
     - 'PaintStyle': 'API/Lua_Constants/PaintStyle.md'
     - 'ScaleType': 'API/Lua_Constants/ScaleType.md'
     - 'TextAlign': 'API/Lua_Constants/TextAlign.md'
     - 'ViewEffect': 'API/Lua_Constants/ViewEffect.md'
  - 'Lua_Demo':
     - 'demo_FlexBox': 'API/Lua_Demo/demo_FlexBox.md'
     - 'demo_Hello': 'API/Lua_Demo/demo_Hello.md'
     - 'demo_Image': 'API/Lua_Demo/demo_Image.md'
     - 'demo_ImageAnimate': 'API/Lua_Demo/demo_ImageAnimate.md'
     - 'demo_ViewChildren': 'API/Lua_Demo/demo_ViewChildren.md'
     - 'demo_Bitmap': 'API/Lua_Demo/demo_Bitmap.md'
     - 'demo_Label': 'API/Lua_Demo/demo_Label.md'
     - 'demo_IconFontLabel': 'API/Lua_Demo/demo_IconFontLabel.md'
     - 'demo_requestFromHttp': 'API/Lua_Demo/demo_requestFromHttp.md'
     - 'demo_Button': 'API/Lua_Demo/demo_Button.md'
     - 'demo_CollectionView': 'API/Lua_Demo/demo_CollectionView.md'
     - 'demo_EmptyRefreshCollectionView': 'API/Lua_Demo/demo_EmptyRefreshCollectionView.md'
     - 'demo_PagerView': 'API/Lua_Demo/demo_PagerView.md'
     - 'demo_ScrollView': 'API/Lua_Demo/demo_ScrollView.md'
     - 'demo_WebView': 'API/Lua_Demo/demo_WebView.md'
     - 'demo_Alert': 'API/Lua_Demo/demo_Alert.md'
     - 'demo_LoadingIndicator': 'API/Lua_Demo/demo_LoadingIndicator.md'
     - 'demo_CustomView': 'API/Lua_Demo/demo_CustomView.md'
     - 'demo_onTouch': 'API/Lua_Demo/demo_onTouch.md'
     - 'demo_Navigation': 'API/Lua_Demo/demo_Navigation.md'
     - 'demo_coroutine': 'API/Lua_Demo/demo_coroutine.md'
     - 'demo_table': 'API/Lua_Demo/demo_table.md'
     - 'demo_Timer': 'API/Lua_Demo/demo_Timer.md'
     - 'demo_Http': 'API/Lua_Demo/demo_Http.md'
     - 'demo_Json': 'API/Lua_Demo/demo_Json.md'
     - 'demo_string': 'API/Lua_Demo/demo_string.md'
     - 'demo_System': 'API/Lua_Demo/demo_System.md'
     - 'demo_CustomError': 'API/Lua_Demo/demo_CustomError.md'
     - 'demo_Customloading': 'API/Lua_Demo/demo_Customloading.md'
     - 'demo_shake': 'API/Lua_Demo/demo_shake.md'
     - 'demo_AudioPlayer': 'API/Lua_Demo/demo_AudioPlayer.md'
     - 'demo_flxNode': 'API/Lua_Demo/demo_flxNode.md'
     - 'demo_DownloadAndFile': 'API/Lua_Demo/demo_DownloadAndFile.md'
     - 'demo_testunits': 'API/Lua_Demo/demo_testunits.md'
     - 'demo_decodeUrl': 'API/Lua_Demo/demo_decodeUrl.md'
     - 'demo_Gesture': 'API/Lua_Demo/demo_Gesture.md'
     - 'demo_testunit': 'API/Lua_Demo/demo_testunit.md'
     - 'demo_luabox': 'API/Lua_Demo/demo_luabox.md'
     - 'demo_callOC': 'API/Lua_Demo/demo_callOC.md'
     - 'demo_Animator': 'API/Lua_Demo/demo_Animator.md'
     - 'demo_matrix': 'API/Lua_Demo/demo_matrix.md'
     - 'demo_init': 'API/Lua_Demo/demo_init.md'
     - 'demo_testunit': 'API/Lua_Demo/demo_testunit.md'



   

