site_name: VideoOS-lua-app
nav:
  - 'OS_Lua 简介': 'OS_Lua.md'
  - 'Android集成说明': 'Android.md'
  - 'iOS集成说明': 'iOS.md'
  - 'lua_View':
     - 'Alert': 'Alert.md'
     - 'Animation': 'Animation.md'
     - 'Button': 'Button.md'
     - 'Canvas': 'Canvas.md'
     - 'CollectionView': 'CollectionView.md'
     - 'CustomPanel': 'CustomPanel.md'
     - 'HScrollView': 'HScrollView.md'
     - 'Image': 'Image.md'
     - 'Label': 'Label.md'
     - 'LoadingDialog': 'LoadingDialog.md'
     - 'LoadingIndicator': 'LoadingIndicator.md'
     - 'Navigation': 'Navigation.md'
     - 'PagerIndicator': 'PagerIndicator.md'
     - 'PagerView': 'PagerView.md'
     - 'RefreshCollectionView': 'RefreshCollectionView.md'
     - 'RefreshTableView': 'RefreshTableView.md'
     - 'ScrollView': 'ScrollView.md'
     - 'StyledString': 'StyledString.md'
     - 'SVGAView': 'SVGAView.md'
     - 'TableView': 'TableView.md'
     - 'TextFiled': 'TextFiled.md'
     - 'Toast': 'Toast.md'
     - 'View': 'View.md'
     - 'WebView': 'WebView.md'