site_name: VideoOS-lua-app
nav:
  - 'OS_Lua 简介': 'OS_Lua.md'
  - 'Android集成说明': 'Android.md'
  - 'iOS集成说明': 'iOS.md'
  - 'lua_View':
     - 'Alert': 'API/Lua_View/Alert.md'
     - 'Animation': 'API/Lua_View/Animation.md'
     - 'Button': 'API/Lua_View/Button.md'
     - 'Canvas': 'API/Lua_View/Canvas.md'
     - 'CollectionView': 'API/Lua_View/CollectionView.md'
     - 'CustomPanel': 'API/Lua_View/CustomPanel.md'
     - 'HScrollView': 'API/Lua_View/HScrollView.md'
     - 'Image': 'API/Lua_View/Image.md'
     - 'Label': 'API/Lua_View/Label.md'
     - 'LoadingDialog': 'API/Lua_View/LoadingDialog.md'
     - 'LoadingIndicator': 'API/Lua_View/LoadingIndicator.md'
     - 'Navigation': 'API/Lua_View/Navigation.md'
     - 'PagerIndicator': 'API/Lua_View/PagerIndicator.md'
     - 'PagerView': 'API/Lua_View/PagerView.md'
     - 'RefreshCollectionView': 'API/Lua_View/RefreshCollectionView.md'
     - 'RefreshTableView': 'API/Lua_View/RefreshTableView.md'
     - 'ScrollView': 'API/Lua_View/ScrollView.md'
     - 'StyledString': 'API/Lua_View/StyledString.md'
     - 'SVGAView': 'API/Lua_View/SVGAView.md'
     - 'TableView': 'API/Lua_View/TableView.md'
     - 'TextFiled': 'API/Lua_View/TextFiled.md'
     - 'Toast': 'API/Lua_View/Toast.md'
     - 'View': 'API/Lua_View/View.md'
     - 'WebView': 'API/Lua_View/WebView.md'
  - 'Lua_Bridge':
     - 'AudioPlayer': 'AudioPlayer.md'
     - 'Data': 'Data.md'
     - 'File': 'File.md'
     - 'Http': 'Http.md'
     - 'Json': 'Json.md'
     - 'Media': 'Media.md'
     - 'Mqtt': 'Mqtt.md'
     - 'Native': 'Native.md'
     - 'Page': 'Page.md'
     - 'System': 'System.md'
     - 'Timer': 'Timer.md'
     - 'Vibrator': 'Vibrator.md'
  - 'Lua_Constants':
     - 'Align': 'Align.md'
     - 'Ellipsize': 'Ellipsize.md'
     - 'FontStyle': 'FontStyle.md'
     - 'FontWeight': 'FontWeight.md'
     - 'Gravity': 'Gravity.md'
     - 'Interpolator': 'Interpolator.md'
     - 'PaintStyle': 'PaintStyle.md'
     - 'ScaleType': 'ScaleType.md'
     - 'TextAlign': 'TextAlign.md'
     - 'ViewEffect': 'ViewEffect.md'


