site_name: VideoOS lua app
repo_url: https://github.com/VideoOS/VideoOS-lua-app
markdown_extensions:
  - admonition
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
nav:
  - 'OS_Lua': 'OS_Lua.md'
  - 'lua_View':
     - 'Alert': 'API/Lua_View/Alert.md'
     - 'Animation': 'API/Lua_View/Animation.md'
     - 'Button': 'API/Lua_View/Button.md'
     - 'Canvas': 'API/Lua_View/Canvas.md'
     - 'CollectionView': 'API/Lua_View/CollectionView.md'
     - 'CustomPanel': 'API/Lua_View/CustomPanel.md'
     - 'HScrollView': 'API/Lua_View/HScrollView.md'
     - 'Image': 'API/Lua_View/Image.md'
     - 'Label': 'API/Lua_View/Label.md'
     - 'LoadingDialog': 'API/Lua_View/LoadingDialog.md'
     - 'LoadingIndicator': 'API/Lua_View/LoadingIndicator.md'
     - 'Navigation': 'API/Lua_View/Navigation.md'
     - 'PagerIndicator': 'API/Lua_View/PagerIndicator.md'
     - 'PagerView': 'API/Lua_View/PagerView.md'
     - 'RefreshCollectionView': 'API/Lua_View/RefreshCollectionView.md'
     - 'RefreshTableView': 'API/Lua_View/RefreshTableView.md'
     - 'ScrollView': 'API/Lua_View/ScrollView.md'
     - 'StyledString': 'API/Lua_View/StyledString.md'
     - 'SVGAView': 'API/Lua_View/SVGAView.md'
     - 'TableView': 'API/Lua_View/TableView.md'
     - 'TextFiled': 'API/Lua_View/TextFiled.md'
     - 'Toast': 'API/Lua_View/Toast.md'
     - 'View': 'API/Lua_View/View.md'
     - 'WebView': 'API/Lua_View/WebView.md'
  - 'Lua_Bridge':
     - 'AudioPlayer': 'API/Lua_Bridge/AudioPlayer.md'
     - 'Data': 'API/Lua_Bridge/Data.md'
     - 'File': 'API/Lua_Bridge/File.md'
     - 'Http': 'API/Lua_Bridge/Http.md'
     - 'Json': 'API/Lua_Bridge/Json.md'
     - 'Media': 'API/Lua_Bridge/Media.md'
     - 'Mqtt': 'API/Lua_Bridge/Mqtt.md'
     - 'Native': 'API/Lua_Bridge/Native.md'
     - 'Page': 'API/Lua_Bridge/Page.md'
     - 'System': 'API/Lua_Bridge/System.md'
     - 'Timer': 'API/Lua_Bridge/Timer.md'
     - 'Vibrator': 'API/Lua_Bridge/Vibrator.md'
  - 'Lua_Constants':
     - 'Align': 'API/Lua_Constants/Align.md'
     - 'Ellipsize': 'API/Lua_Constants/Ellipsize.md'
     - 'FontStyle': 'API/Lua_Constants/FontStyle.md'
     - 'FontWeight': 'API/Lua_Constants/FontWeight.md'
     - 'Gravity': 'API/Lua_Constants/Gravity.md'
     - 'Interpolator': 'API/Lua_Constants/Interpolator.md'
     - 'PaintStyle': 'API/Lua_Constants/PaintStyle.md'
     - 'ScaleType': 'API/Lua_Constants/ScaleType.md'
     - 'TextAlign': 'API/Lua_Constants/TextAlign.md'
     - 'ViewEffect': 'API/Lua_Constants/ViewEffect.md'
  - 'Lua_Demo':
     - 'demoA_FlexBox': 'API/Lua_Demo/demoA_FlexBox.lua'
     - 'demoA_Hello': 'API/Lua_Demo/demoA_Hello.lua'
     - 'demoA_Image': 'API/Lua_Demo/demoA_Image.lua'
     - 'demoA_ImageAnimate': 'API/Lua_Demo/demoA_ImageAnimate.lua'
     - 'demoA_ViewChildren': 'API/Lua_Demo/demoA_ViewChildren.lua'
     - 'demoB_Bitmap': 'API/Lua_Demo/demoB_Bitmap.lua'
     - 'demoC_Label': 'API/Lua_Demo/demoC_Label.lua'
     - 'demoC2_IconFontLabel': 'API/Lua_Demo/demoC2_IconFontLabel.lua'
     - 'demoD_requestFromHttp': 'API/Lua_Demo/demoD_requestFromHttp.lua'
     - 'demoE_Button': 'API/Lua_Demo/demoE_Button.lua'
     - 'demoH2_CollectionView': 'API/Lua_Demo/demoH2_CollectionView.lua'
     - 'demoH2_EmptyRefreshCollectionView': 'API/Lua_Demo/demoH2_EmptyRefreshCollectionView.lua'
     - 'demoK_PagerView': 'API/Lua_Demo/demoK_PagerView.lua'
     - 'demoK_ScrollView': 'API/Lua_Demo/demoK_ScrollView.lua'
     - 'demoK_WebView': 'API/Lua_Demo/demoK_WebView.lua'
     - 'demoL_Alert': 'API/Lua_Demo/demoL_Alert.lua'
     - 'demoL_LoadingIndicator': 'API/Lua_Demo/demoL_LoadingIndicator.lua'
     - 'demoL2_CustomView': 'API/Lua_Demo/demoL2_CustomView.lua'
     - 'demoL3_onTouch': 'API/Lua_Demo/demoL3_onTouch.lua'
     - 'demoM_Navigation': 'API/Lua_Demo/demoM_Navigation.lua'
     - 'demoO_coroutineDemo': 'API/Lua_Demo/demoO_coroutineDemo.lua'
     - 'demoO_table': 'API/Lua_Demo/demoO_table.lua'
     - 'demoO_Timer': 'API/Lua_Demo/demoO_Timer.lua'
     - 'demoP_Http': 'API/Lua_Demo/demoP_Http.lua'
     - 'demoP_Json': 'API/Lua_Demo/demoP_Json.lua'
     - 'demoP_string': 'API/Lua_Demo/demoP_string.lua'
     - 'demoP_System': 'API/Lua_Demo/demoP_System.lua'
     - 'demoV1_CustomError': 'API/Lua_Demo/demoV1_CustomError.lua'
     - 'demoV1_Customloading': 'API/Lua_Demo/demoV1_Customloading.lua'
     - 'demoW1_shake': 'API/Lua_Demo/demoW1_shake.lua'
     - 'demoW2_AudioPlayer': 'API/Lua_Demo/demoW2_AudioPlayer.lua'
     - 'demoY2_flxNode': 'API/Lua_Demo/demoY2_flxNode.lua'
     - 'demoY5_DownloadAndFile': 'API/Lua_Demo/demoY5_DownloadAndFile.lua'
     - 'demoZ_2015_testunit': 'API/Lua_Demo/demoZ_2015_testunit.lua'
     - 'demoZ_decodeUrl': 'API/Lua_Demo/demoZ_decodeUrl.lua'
     - 'demoZ_Gesture': 'API/Lua_Demo/demoZ_Gesture.lua'
     - 'demoZ_testunit': 'API/Lua_Demo/demoZ_testunit.lua'
     - 'demoZ1_luabox': 'API/Lua_Demo/demoZ1_luabox.lua'
     - 'demoZ2_callOC': 'API/Lua_Demo/demoZ2_callOC.lua'
     - 'demoZB1_Animator': 'API/Lua_Demo/demoZB1_Animator.lua'
     - 'demoZZ_matrix': 'API/Lua_Demo/demoZZ_matrix.lua'
     - 'init': 'API/Lua_Demo/init.lua'
     - 'demoZ_testunit': 'API/Lua_Demo/demoZ_testunit.lua'



   

